### ISSUE TITLE
How to generate apis' json

### ISSUE THREAD

**Issue by drancom** [terraswap/terraswap-web-app#145]
I am reading the codes in the repo and I am wonder how to generate the apis' json files such as https://api-pisco.terraswap.io/tokens or https://api.terraswap.io/tokens.

Could you tell me where I can find the code for them and/or explain how they are generated?

Thank you

**Comment by JoowonYun** [comment]
Here. https://github.com/terraswap/terraswap-service

**Comment by drancom** [comment]
Thank you for the link. However, I got 404 error. :(
Could you help me to access the service?
![image](https://user-images.githubusercontent.com/4931203/203712695-676fb293-6989-4b0f-8799-e3297979f594.png)

**Comment by JoowonYun** [comment]
Ah, now it's public.

**Comment by drancom** [comment]
Yeah. I can see it now. Thank you!
