### ISSUE TITLE
Support from-to token direct select by URI query

### ISSUE THREAD

**Issue by psy2848048** [terraswap/terraswap-web-app#19]
`app.terraswap.io?from=tokenContract1orNativeTokenDenom&to=tokenContract2orNativeTokenDenom`

**Comment by JoowonYun** [comment]
+ To keep the existing input value when push to `Trying again` button.

**Comment by rromanovsky** [comment]
Also you'll be able to share the link with predefined tokens which is a very nice feature to have 👀
