### ISSUE TITLE
Fee error "must be at least x.xx UST to pay the fee." is kind of vague.

### ISSUE THREAD

**Issue by ontvzla** [terraswap/terraswap-web-app#20]
Not sure how the format for issues/enhancements should be. Tried to look for more information but couldn't find any.

## Description 
When trying to swap I get the error under the From control "must be at least x.xx UST to pay the fee.". I am assuming I am getting the error because my balance in UST is zero.  The behavior is kind of weird because the From control shows a red border implying there is an error with that field but at the same time the error message mentions the **fee** for the transaction. I believe something in the order of "**You don't have enough balance to pay for x.xx UST fee.**" would be more clear. Again, that is what I am assuming maybe the current error refers to something else.

## Issue reproduction
With zero balance on UST do the following:
* Select mBTC on the From control.
* Select UST on Fee control.
* Select UST on To control.
* Click on MAX option to swap max available balance from mBTC.
* Get error on From Control.

**Comment by honeymaro** [comment]
Thanks for your report. :)

We haven't specified a format for writing issues yet. So feel free to leave your comments. We'll set up a format when issues get difficult to manage.
