### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by gududefengzhong** [terraswap/terraswap-web-app#46]
hi, sir:
    i am a big fan of terraswap, yagmi.
    I encountered a problem, exactly speaking, its a bug.

【normal case】
when my mouse put in the [connect] button, it will give me a hover style
![image](https://user-images.githubusercontent.com/7471735/139895164-62ac7c5a-d105-4db3-871e-8865f328873f.png)

【wired case】
when i turn the scroll bar down to some place where box1 and box2 in the same horizon line, users cannot click the 【connect】 button to connect

![image](https://user-images.githubusercontent.com/7471735/139898081-45ed35f7-5f68-485a-8e81-ba135aef0418.png)

【device】
mac book pro 14 inch
os:  mac
browser: google chrome,  95.0.4638.54 (version)

If  you guys do  not know what i  mean, dm me via  https://twitter.com/rochestor_mu

Wish you guys will make it in the near future

**Comment by honeymaro** [comment]
Hi. This issue has been fixed with several updates. 

Thank you for your report.
And sorry for the late reply. 

Have a wonderful day!
