### ISSUE TITLE
Chrome freezes due to infinity loop

### ISSUE THREAD

**Issue by marceltoma** [terraswap/terraswap-web-app#84]
Hi,
When I fill the fields to do a swap in chrome in linux, it enters an infinity loop that freezes chrome and obligates me to close all chrome windows.
![2022-03-08_20-36](https://user-images.githubusercontent.com/2895189/157344295-4767e11c-d9c4-4ee7-aca2-54d3e96ad9bc.png)

Chrome Version
Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by JoowonYun** [comment]
When a block is newly created, it is simulated again periodically.

Are there other situations you can reproduce?

**Comment by honeymaro** [comment]
This issue has been resolved and will be in the next release. thank you!
